name: Infra Build & Deploy Weather App

on:
  push:
    branches:
      - main

jobs:
#Commented to automatically run pipleine
  # plan:
  #   name: Terraform Plan
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: 1.6.0   

  #     - name: Initialize Terraform
  #       run: terraform init

  #     - name: Run Terraform Plan
  #       run: terraform plan -var="sp_object_id=$SP_OBJECT_ID"

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      SP_OBJECT_ID: ${{ secrets.SP_OBJECT_ID }}
    #needs: plan
    #environment: terraform-apply  # Triggers manual approval

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          cli_config_credentials_token: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Set Azure Credentials
        run: |
          echo "Setting up Azure credentials for Terraform..."
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: 
          terraform plan -var="sp_object_id=$SP_OBJECT_ID"
      
      - name: Apply Terraform Changes
        run: 
          terraform apply --auto-approve -var="sp_object_id=$SP_OBJECT_ID"

      - name: Save VM Public IP as Artifact
        run: |
           terraform output -raw public_ip > vm_ip.txt
        shell: bash

      - name: Upload VM IP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vm-ip
          path: vm_ip.txt

  deploy:
    name: Deploy Weather App
    runs-on: ubuntu-latest
    needs: apply

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Azure Credentials
        run: |
          echo "Setting up Azure credentials for Terraform..."
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Retrieve private key from Azure Key Vault
        id: get-private-key
        run: |
          az keyvault secret show --vault-name ${{ secrets.KEYVAULT_NAME }} --name vm-ssh-key --query value -o tsv > private_key.pem
          chmod 600 private_key.pem


      - name: Download VM IP from Artifact
        uses: actions/download-artifact@v4
        with:
          name: vm-ip

      - name: Read VM IP
        run: |
          VM_IP=$(cat vm_ip.txt)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

      # - name: Login to Azure
      #   uses: Azure/login@v1
      #   with:
      #     auth-type: SERVICE_PRINCIPAL
      #     subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      #     client-id: ${{ secrets.ARM_CLIENT_ID }}
      #     tenant-id: ${{ secrets.ARM_TENANT_ID }}
      #     enable-AzPSSession: true

      - name: Deploy Python App to Azure VM
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem weather.py weatheruser@$VM_IP:/home/weatheruser/weather.py
          ssh -t -o StrictHostKeyChecking=no -i private_key.pem weatheruser@$VM_IP << 'EOF'
          sudo apt update && sudo apt install -y python3 python3-pip
          echo "API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env
          pip3 install flask requests gunicorn
          python3 weather.py
          nohup gunicorn -w 4 -b 0.0.0.0:80 app:app &
          EOF
        env:
          VM_IP: ${{ env.VM_IP }}
